### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by gjohnson**
Couple things...

1) Removed the hook stuff for now, I added it originally but it doesn't work well at all. Need to rethink it.

2.) Needed control over the ordering of the question at the prompt, so now the questions are explicitly set in the `khaos.json` file. The `prompt` value can be anything that [prompt-for](https://github.com/segmentio/prompt-for) supports. Not quite as clean as parsing the template variables but order is important. :-/

I guess we could have it flag or something so we get the implicit clean stuff by default? Totally up for some ideas here because we NEED order but that magic prompt from templates is hawt too.... Halp!

```json
{
  "source": "....",
  "destination": "...",
  "prompt": [
    "name",
    "endpoint",
    "docs",
    "mapper",
    "track",
    "identify",
    "alias",
    "group",
    "page",
    "screen"
  ]
}
```

3) Added middleware API for adding metalsmith plugins.

```js
khaos.use(function(metalsmith, files, done) {
  var meta = metalsmith.metadata();
  meta.project = slug(meta.name);
  return done();
});
```

4) Added helper API for defining custom handlebar helpers.

```js
khaos.helper('slug', function(str){
  return str.toLowerCase()
  .replace(/^ +| +$/g, '')
  .replace(/\s+/g, '-')
  .replace(/[^a-z0-9\-]/g, '');
});
```

5) Added support for a "main" module to be defined in templates. The khaos instance is passed to the function exported from `index.js`, this is where you can decorate away via `.use(fn)` and `.helper(fn)`. Programmatically doing it now so I can ship some stuff for our partners to use and mucking around with the path resolving will take too long, but the next iteration will support plugin definitions in the config file just like metalsmith.

```js
module.exports = function(khaos){
  khaos.helper('slug', slug);
  khaos.use(function(metalsmith, files, done) {
    var meta = metalsmith.metadata();
    meta.project = slug(meta.name);
    return done();
  });
};
```

@ianstormtaylor @MatthewMueller @yields

### CODE REVIEW

**Comment by MatthewMueller** [comment]
Sweet!

For 2.) Haven't been following too closely, but why is order important?

**Comment by gjohnson** [comment]
@MatthewMueller I have a template that prompts app `name`, and then various methods (`track`, `alias`, etc). Right now it goes like: `alias (y/n): ` then `name: .... ` and then `track (y/n): `, so it looks funny with the name in the middle :-)

**Comment by MatthewMueller** [comment]
ahh okay. one this we could do it kinda have Textmate style fill-ins. I'm forgetting the syntax exactly , but something like:

`{1:name}, {2:track}, ...`

Kinda sucks that you have to keep the order up to date across files, but there might be a way around that too.

**Comment by ianstormtaylor** [comment]
Boooooom this is sick.

For (1) sounds like a good call, that stuff is super tricky. Let's start a new issue for it since it'll probably get complicated fast.

For (2) what if we made it called something like `order` or `prompts` and then it just was always used as a way to order the prompts, and defaulted to an empty `[]`. So we could even do `['name']` only, and that would just ensure that name is first, and everything else would be whatever, or we can get anal when needed too. I def agree that keeping the super-simple case of auto-prompting from a simple template seems like something we should keep, for pure sexiness/simplicity.

For (3) and (4) sounds great!

And for (5) that is freaking genius, love how that works.

**Comment by gjohnson** [comment]
@ianstormtaylor I dig the ordering only idea. Will do!

**Comment by yields** [comment]
awesome! really like the helper api, really needed that.

**Comment by gjohnson** [comment]
@ianstormtaylor i assume your picking parts worth picking out of this branch and I can close now. Cool?

**Comment by ianstormtaylor** [comment]
@gjohnson Yezzir! Got `order` for the ordering, got the `before/after` hooks and got the `main` handling too!

**Pull request closed without merging**
